USE [master]
GO

/****** Object:  Database [bondiva]    Script Date: 10/07/2022 14:14:20 ******/
CREATE DATABASE [bondiva]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'bondiva', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\bondiva.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'bondiva_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\bondiva_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bondiva].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [bondiva] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [bondiva] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [bondiva] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [bondiva] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [bondiva] SET ARITHABORT OFF 
GO

ALTER DATABASE [bondiva] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [bondiva] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [bondiva] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [bondiva] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [bondiva] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [bondiva] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [bondiva] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [bondiva] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [bondiva] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [bondiva] SET  DISABLE_BROKER 
GO

ALTER DATABASE [bondiva] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [bondiva] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [bondiva] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [bondiva] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [bondiva] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [bondiva] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [bondiva] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [bondiva] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [bondiva] SET  MULTI_USER 
GO

ALTER DATABASE [bondiva] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [bondiva] SET DB_CHAINING OFF 
GO

ALTER DATABASE [bondiva] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [bondiva] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [bondiva] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [bondiva] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [bondiva] SET QUERY_STORE = OFF
GO

ALTER DATABASE [bondiva] SET  READ_WRITE 
GO

